name: CI-CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_S3_URL: ${{AWS_S3_URL}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Build Docker Image
        run: docker build -t rkdtlsgml40/cookingdom:latest .

      - name: Publish To Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rkdtlsgml40/cookingdom:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
